[app]
title = """
            # 📊 Предобработка данных о стоимости недвижимости в Мумбаи
            """
page_info = "Эта страница позволяет в интерактивном режиме предобработать данные о стоимости домов в Мумбаи"

[start_df]
describe_features = """
- ``` price ``` - цена (__рупии__)
- ``` area ``` - область (__кв.м__)
- ``` latitude ``` - широта 
- ``` longitude ``` - долгота
- ``` Bedrooms ``` - количество спален
- ``` Bathrooms ``` - количество душевых
- ``` Balcony ``` - количество балконов 
- ``` Status ``` - статус постройки (__в разработке__/__готово к заселению__)
- ``` neworold ``` - тип объекта недвижимости (__новое__/__вторичное__)
- ``` parking ``` - количество парковочных мест 
- ``` Furnished_status ``` - статус обустройства объекта (__обустроено__/__частично-обустроено__/__необустроено__)
- ``` Lift ``` - количество лифтов 
- ``` type_of_building ``` - тип строения (__квартира__/__частный дом__)

"""
data_analysis = """ 
    - Наблюдаются пропуски у категориальных признаков: ```Furnished_status```, ```Status```
                 
    - Тепловая карта показывает высокую корреляцию цены жилья (```price```) с:
        - площадью ${0.71}$
        - координатой по широте ${-0.44}$
        - количеством спальнь ${0.56}$
        - количеством душевых ${0.63}$
    
    - Высокая корреляция (${1}$) между ```Balcony```, ```parking```, ```Lift```
    - По географической карте видна зависимость цены жилья от его расположения
    - В основном цена представлена круглым числом, что дополнительно занимает лишнию память
                 
    """
reports = """
    - Высокая корреляция между количествами лифтов, парковок и балконов, причём у всех трёх признаков корреляция 
    с ценой довольно низкая. Данные признаки в основном являются характеристиками **многоквартирных домов**, которые 
    строятся по некоторому стандарту с определённым количеством каждой категории. В современных реалях, наличие всех 
    трёх факторов в многоквартирных домах не является премиальным признаком
    -  Большая корреляция между количествами ванных комнат и спален. 
    Данная зависимость объясняется **культурой**, распространённой в Мумбаи: 
    принято иметь отдельную ванную комнату для каждой спальни.
    - Изменим единицу измерения цены (```price```) с **рупий** на **млн.рупий**
    - Датафрейм занимает много памяти, следует изменить типы данных некоторых признаков на ресурсно-экономные
"""
[diagrams]
scatter = """
    инструмент качества, с помощью которого устанавливают зависимость между двумя типами данных.
                     
    **Некоторые варианты корреляции парных данных на диаграмме разброса**
    - **Прямая положительная корреляция**
        - Кластер точек представлен узкой областью
        - Прямая, возрастающая линия
    - **Слабая положительная корреляция**
        - Кластер точек представлен широкой областью
    - **Отсутствие корреляции**
        - Чётко определённого кластера точек нет
    - **Отрицательная корреляция**
        - Кластер точек представлен узкой областью
        - Прямая, убывающая линия
    - **Слабая отрицательная корреляция**
        - Кластер представлен широкой областью
"""
hot_map = """
                - **Тепловая карта**  - графический способ представления данных, который помогает определить влияние признаков друг на друга (_корреляция_)
                - **Корреляция** - статистическая мера, которая определяет степень взаимосвязи между двумя переменными. 
                    - Значения корреляции варьируются от **-1** до **1**
                    - Чем выше значение - тем больше прямая зависимость признаков ⬆️⬆️
                    - Чем меньше значение - тем больше обратная зависимость признаков ⬆️⬇️
                    - Признаки с высоким **модулем** значения корреляции полезны в решении задач ML 
                 """

[helps]
handle_missing = "Заполнить пропущенные значения выбранным методом"
imput_method = """Выберите, как заполнить пропуски: среднее, медиана или наиболее частое значение.
_Категориальные по умолчанию заполняются часто встречающимся значением_"""
encode = "Преобразовать категориальные признак в числовой формат"
encode_method = "**one-hot** создаёт новые столбцы, **label** присваивает числовые метки"
select_cols = "Какие столбцы останутся"


[links]
start_dataset = """
    Исходный датасет находится по ссылке: [GoogleDrive](https://drive.google.com/file/d/1mpuQWoBEVsAYL7JIMvkAHkdaKtLOz_b2/view)
"""
