[app]
title = "💡Обученные модели"

[sidebar]
models_name = "Модели"

[helps]
sidebar_help = """Введите характеристики и узнайте потенциальную стоимость инетересующего вас жилья в Мумбаи"""

[mapa]
description = """
Карта демонстрирует **точность** предсказаний модели в соответствии с реальными значениями цен жилья в Мумбаи.

🟢 - Совпадение с реальным значением в пределах погрешности, равной ```MAE``` 

🔴 - Несовпадение с реальным значением

"""

[graphic]
name = "График плотности распределения точных и предсказанных значений"

distplot = """
График **Distplot** отображает кривую, наложенную на гистограмму, которая непрерывно аппроксимирует плотности вероятности данных.

В данном случае график помогает понять, как сильно плотность распределения **предсказанных** данных отличается от **действительных**. 

"""
