[linear]
description = """
**Линейная регрессия** — это математическая модель, которая описывает связь нескольких переменных. 

**Цель линейной регрессии** - 
- Найти коэффициенты уравнения (гиперплоскости) ${y = b_0 + b_1x_1+b_2x_2 ... b_nx_n}$,  которые наилучшим образом описывают данные.
    - ${y}$ - зависимая переменная (в нашем случае ```price```)
    - ${x_1, x_2, ... x_n}$ - независимые переменные (остальные признаки)
"""

[br]
description = """
**BaggingRegression** - метод, при котором для регрессии усредняются результаты нескольких моделей.

**Суть:** 
- Базовые модели обучаются на разных подмножествах данных 
- Прогнозы объединяются, что улучшает способность к обобщению
- Снижает риск переобучения
"""

[sr]
description = """
**StackingRegression** - метод, который комбинирует предсказания нескольких базовых моделей с помощью **мета-модели** (финального регрессора). 

**Суть метода:** 
- Выбирается набор разных регрессеров, каждый из которых обучается на выборке
- Предсказания всех моделей собираются в новый набор
- Мета модель обучается на этом наборе, чтобы комбинировать предсказания и выдавать финальный результат
"""
[gbr]
description = """
**GradientBoostingRegression** - метод, основанный на градиентном бустинге, который **последовательно** строит слабые модели (деревья решений) для минимизации ошибки.

**Суть метода:**
- Модель начинается с простого предсказания
- На каждой итерации строится новое дерево решений, которое корректирует ошибки предыдующих деревьев (учится на ошибках)
- Ошибки вычисляются как градиент функции потерь
- **Финальное предсказание** - это взвешенная сумма предсказаний всех деревьев

"""


[catboost]
description = """
**CatBoostRegressor** - это реализация градиентного бустинга от компании [Яндекс](https://catboost.ai/?ysclid=maflbfun1g968169241), оптимизированная для работы с категориальными признаками.

**Характеристики метода**
- Как в ```GradientBoosting``` **CatBoost** строит последовательность деревьер, минимизируя функцию потерь с помощью градиентного спуска
- Встроенные механизмы борьбы с переобучением
"""
[metrics]
help = """
**MAE** (Mean Absolute Error) - измеряет _среднюю абсолютную ошибку_ между предсказанными и реальными значениями. Показывает насколько в среднем предсказания модели отклюняются от истинных значений.

**MSE** (Mean Squared Error) - измеряет _среднеквадратичную ошибку_. Более чувствительна к большим ошибкам, чем **MAE**. Полезна там, где нужно минимизировать ошибки.

**RMSE** (Root Mean Squared Error) - квадратный корень из **MSE**. Учитывает как средние, так и большие ошибки.

**MAPE** (Mean Absolute Percentage error) -  измеряет отклонение прогнозов от фактических значений **в процентах**. Является хорошим выбором, когда нужно легко интерпретируемое показание ошибки в процентном отношении.

**${R^2}$**  - измеряет долю дисперсии. Значение ближе к 1 указывает на хорошую модель. Метрика показывает, насколько хорошо модель объясняет вариативность данных. 

"""
